import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const DICT = {
  en: {
    home: "Home",
    course: "Course",
    aboutUs: "About Us",
    contact: "Contact",
    enroll: "Enroll",
    search: "Search...",
    signIn: "Sign In",
    signUp: "Sign up",
    logout: "Logout",
    accountSettings: "Account Setting",
    adminDashboard: "Admin Dashboard",
    searchCourses: "Searching Courses ...",
    schoolCourse: "School Course",
    latestNews: "Latest News",
    noCourses: "No courses found",
    enrollClass: "Enroll Class",
    enrollCourse: "Enroll Course",
    goBack: "Go Back",
    pageNotFound: "Page Not Found",
    pageNotFoundDesc: "Sorry, the page you're looking for doesn't exist or may have been moved.",
    accessForbidden: "Access Forbidden",
    accessForbiddenDesc: "You don't have permission to view this page. If you believe this is a mistake, please contact the administrator.",
    allCourses: "All Courses",
    inCategory: "in",
  },
  kh: {
    // Navigation / layout
    home: "ទំព័រដើម",
    course: "វគ្គសិក្សា",
    aboutUs: "អំពីយើង",
    contact: "ទំនាក់ទំនង",
    enroll: "ចុះឈ្មោះ",
    search: "ស្វែងរក...",
    signIn: "ចូល",
    signUp: "ចុះឈ្មោះ",
    logout: "ចាកចេញ",
    accountSettings: "ការកំណត់គណនី",
    adminDashboard: "ផ្ទាំងគ្រប់គ្រង",
    searchCourses: "ស្វែងរកវគ្គសិក្សា ...",
    schoolCourse: "វគ្គសិក្សាសាលា",
    latestNews: "ព័ត៌មានថ្មីៗ",
    noCourses: "រកមិនឃើញវគ្គសិក្សា",
    enrollClass: "ចូលរៀន",
    enrollCourse: "ចុះឈ្មោះវគ្គ",
    goBack: "ត្រឡប់ក្រោយ",
    pageNotFound: "រកទំព័រមិនឃើញ",
    pageNotFoundDesc: "សូមទោស ទំព័រដែលអ្នកកំពុងស្វែងរកមិនមាន ឬអាចត្រូវបានផ្លាស់ប្តូរ។",
    accessForbidden: "ការចូលប្រើត្រូវបានហាមឃាត់",
    accessForbiddenDesc: "អ្នកមិនមានសិទ្ធិមើលទំព័រនេះទេ។ ប្រសិនបើអ្នកគិតថានេះជាកំហុស សូមទាក់ទងអ្នកគ្រប់គ្រង។",

    // Login / Register (public)
    "Welcome Back": "សូមស្វាគមន៍ត្រឡប់មកវិញ",
    "Sign in to your account to continue": "ចូលគណនីរបស់អ្នកដើម្បីបន្ត",
    "Don't have an account?": "មិនទាន់មានគណនី?",
    "Create an account": "បង្កើតគណនី",
    "Create Account": "បង្កើតគណនី",
    "Create a new administrator account for the CIU management system.": "បង្កើតគណនីអ្នកគ្រប់គ្រងថ្មីសម្រាប់ប្រព័ន្ធគ្រប់គ្រង CIU។",
    "Already have an account?": "មានគណនីរួចហើយ?",
    "Sign in": "ចូល",
    "Sign In": "ចូល",
    "Sign in with Google": "ចូលតាម Google",
    "Sign in with Apple": "ចូលតាម Apple",
    "Sign in with Facebook": "ចូលតាម Facebook",
    "Sign up with Google": "ចុះឈ្មោះតាម Google",
    "Sign up with Apple": "ចុះឈ្មោះតាម Apple",
    "Sign up with Facebook": "ចុះឈ្មោះតាម Facebook",
    "Google": "Google",
    "or": "ឬ",
    "Email": "អ៊ីមែល",
    "Email address": "អាសយដ្ឋានអ៊ីមែល",
    "Enter your email address": "បញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក",
    "Username": "ឈ្មោះអ្នកប្រើ",
    "Enter your username": "បញ្ចូលឈ្មោះអ្នកប្រើ",
    "Enter username": "បញ្ចូលឈ្មោះអ្នកប្រើ",
    "Enter email address": "បញ្ចូលអាសយដ្ឋានអ៊ីមែល",
    "Password": "ពាក្យសម្ងាត់",
    "Enter your password": "បញ្ចូលពាក្យសម្ងាត់",
    "Create a password": "បង្កើតពាក្យសម្ងាត់",
    "Enter password": "បញ្ចូលពាក្យសម្ងាត់",
    "Hide password": "លាក់ពាក្យសម្ងាត់",
    "Show password": "បង្ហាញពាក្យសម្ងាត់",
    "Repeat password": "បញ្ចូលពាក្យសម្ងាត់ម្តងទៀត",
    "Repeat your password": "បញ្ចូលពាក្យសម្ងាត់ម្តងទៀត",
    "Phone number": "លេខទូរសព្ទ",
    "Phone": "ទូរសព្ទ",
    "Phone number (optional)": "លេខទូរសព្ទ (ស្រេចចិត្ត)",
    "By signing up, you agree to our": "តាមរយៈការចុះឈ្មោះ អ្នកយល់ព្រមនឹង",
    "Terms": "លក្ខខណ្ឌ",
    "and": "និង",
    "Privacy Policy": "គោលការណ៍ឯកជនភាព",
    "Forgot Password?": "ភ្លេចពាក្យសម្ងាត់?",
    "Forgot password?": "ភ្លេចពាក្យសម្ងាត់?",
    "Signing in...": "កំពុងចូល...",
    "Creating account...": "កំពុងបង្កើតគណនី...",
    "Get started with a free account at Cambodia International University": "ចាប់ផ្តើមជាមួយគណនីឥតគិតថ្លៃនៅសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា",
    "Invalid credentials": "ព័ត៌មានចូលមិនត្រឹមត្រូវ",
    "Server error, please try again": "កំហុសម៉ាស៊ីនមេ សូមព្យាយាមម្តងទៀត",
    "Server error, please try again.": "កំហុសម៉ាស៊ីនមេ សូមព្យាយាមម្តងទៀត។",
    "Password don't match": "ពាក្យសម្ងាត់មិនត្រូវគ្នា",
    "Invalid email": "អ៊ីមែលមិនត្រឹមត្រូវ",

    // Student auth
    "Student Login": "ចូលសិស្ស",
    "Student Register": "ចុះឈ្មោះសិស្ស",
    "Student Registration": "ការចុះឈ្មោះសិស្ស",
    "Welcome back! Sign in to access your courses and grades.": "សូមស្វាគមន៍ត្រឡប់មកវិញ! ចូលដើម្បីចូលមើលវគ្គសិក្សា និងពិន្ទុរបស់អ្នក។",
    "Create one": "បង្កើតមួយ",
    "Regular User Login": "ចូលអ្នកប្រើធម្មតា",
    "Regular User Register": "ចុះឈ្មោះអ្នកប្រើធម្មតា",
    "Join Cambodia International University and start your academic journey.": "ចូលរួមសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា ហើយចាប់ផ្តើមដំណើរសិក្សារបស់អ្នក។",
    "Student registered successfully!": "សិស្សបានចុះឈ្មោះដោយជោគជ័យ!",
    "Go to Student Login": "ទៅកាន់ទំព័រចូលសិស្ស",
    "Full name": "ឈ្មោះពេញ",
    "Optional": "ស្រេចចិត្ត",
    "Registering...": "កំពុងចុះឈ្មោះ...",
    "Register": "ចុះឈ្មោះ",
    "Username, email, and password are required.": "ឈ្មោះអ្នកប្រើ អ៊ីមែល និងពាក្យសម្ងាត់ តម្រូវឱ្យបំពេញ។",
    "Registration failed.": "ការចុះឈ្មោះបរាជ័យ។",

    // Teacher auth
    "Teacher Login": "ចូលគ្រូ",
    "Teacher Registration": "ការចុះឈ្មោះគ្រូ",
    "Teacher Register": "ចុះឈ្មោះគ្រូ",
    "Welcome back! Sign in to manage your classes and students.": "សូមស្វាគមន៍ត្រឡប់មកវិញ! ចូលដើម្បីគ្រប់គ្រងថ្នាក់ និងសិស្សរបស់អ្នក។",
    "Student Login": "ចូលសិស្ស",
    "Create your teacher account at Cambodia International University.": "បង្កើតគណនីគ្រូរបស់អ្នកនៅសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា។",
    "Teacher registered successfully!": "គ្រូបានចុះឈ្មោះដោយជោគជ័យ!",
    "Go to Teacher Login": "ទៅកាន់ទំព័រចូលគ្រូ",

    // Admin auth
    "Admin Login": "ចូលអ្នកគ្រប់គ្រង",
    "Admin Registration": "ការចុះឈ្មោះអ្នកគ្រប់គ្រង",
    "Welcome back, admin. Sign in to manage Cambodia International University.": "សូមស្វាគមន៍ត្រឡប់មកវិញ អ្នកគ្រប់គ្រង។ ចូលដើម្បីគ្រប់គ្រងសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា។",
    "Don't have an admin account?": "មិនមានគណនីអ្នកគ្រប់គ្រង?",
    "Register as admin": "ចុះឈ្មោះជាអ្នកគ្រប់គ្រង",
    "Remember me": "ចងចាំខ្ញុំ",
    "Please enter both email and password.": "សូមបញ្ចូលទាំងអ៊ីមែល និងពាក្យសម្ងាត់។",
    "Invalid email or password.": "អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។",
    "Admin registered successfully!": "អ្នកគ្រប់គ្រងបានចុះឈ្មោះដោយជោគជ័យ!",
    "Go to Admin Login": "ទៅកាន់ទំព័រចូលអ្នកគ្រប់គ្រង",
    "All fields are required.": "គ្រប់វាលទាំងអស់ត្រូវបានទាមទារ។",

    // Forgot / Reset / Verify
    "Forgot Password?": "ភ្លេចពាក្យសម្ងាត់?",
    "Enter your email and we'll send you a reset link": "បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើតំណកំណត់ពាក្យសម្ងាត់ឡើងវិញ",
    "Sending...": "កំពុងផ្ញើ...",
    "Send Reset Link": "ផ្ញើតំណកំណត់ឡើងវិញ",
    "Remember your password?": "ចងចាំពាក្យសម្ងាត់របស់អ្នក?",
    "Email not found": "រកមិនឃើញអ៊ីមែល",
    "Server not reachable": "មិនអាចភ្ជាប់ម៉ាស៊ីនមេ",
    "Check Your Email": "ពិនិត្យអ៊ីមែលរបស់អ្នក",
    "We sent a password reset link to": "យើងបានផ្ញើតំណកំណត់ពាក្យសម្ងាត់ឡើងវិញទៅកាន់",
    "Back to Login": "ត្រឡប់ទៅទំព័រចូល",
    "I have a reset code — enter it here": "ខ្ញុំមានលេខកូដកំណត់ឡើងវិញ — បញ្ចូលនៅទីនេះ",
    "Verify your email": "ផ្ទៀងផ្ទាត់អ៊ីមែលរបស់អ្នក",
    "Verify email": "ផ្ទៀងផ្ទាត់អ៊ីមែល",
    "We sent a 6-digit code to": "យើងបានផ្ញើលេខកូដ ៦ ខ្ទង់ទៅកាន់",
    "Didn't receive the code?": "មិនទទួលបានលេខកូដ?",
    "Resend": "ផ្ញើម្តងទៀត",
    "Verifying...": "កំពុងផ្ទៀងផ្ទាត់...",
    "Please enter all 6 digits": "សូមបញ្ចូលលេខ ៦ ខ្ទង់ទាំងអស់",
    "Invalid code": "លេខកូដមិនត្រឹមត្រូវ",
    "New code sent": "លេខកូដថ្មីត្រូវបានផ្ញើ",
    "Password Reset": "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
    "Reset Password": "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
    "Your password has been reset successfully. You can now sign in with your new password.": "ពាក្យសម្ងាត់របស់អ្នកត្រូវបានកំណត់ឡើងវិញដោយជោគជ័យ។ ឥឡូវអ្នកអាចចូលជាមួយពាក្យសម្ងាត់ថ្មីរបស់អ្នក។",
    "Enter the reset code from your email and choose a new password": "បញ្ចូលលេខកូដកំណត់ឡើងវិញពីអ៊ីមែលរបស់អ្នក ហើយជ្រើសរើសពាក្យសម្ងាត់ថ្មី",
    "Reset code": "លេខកូដកំណត់ឡើងវិញ",
    "Enter the reset code / token": "បញ្ចូលលេខកូដ / តូខេន",
    "New password": "ពាក្យសម្ងាត់ថ្មី",
    "At least 6 characters": "យ៉ាងតិច ៦ តួអក្សរ",
    "Confirm new password": "បញ្ជាក់ពាក្យសម្ងាត់ថ្មី",
    "Re-enter the new password": "បញ្ចូលពាក្យសម្ងាត់ថ្មីម្តងទៀត",
    "Resetting...": "កំពុងកំណត់ឡើងវិញ...",
    "Haven't requested a reset?": "មិនទាន់បានស្នើសុំកំណត់ឡើងវិញ?",
    "Request one": "ស្នើសុំមួយ",
    "Reset code and new password are required.": "លេខកូដកំណត់ឡើងវិញ និងពាក្យសម្ងាត់ថ្មីត្រូវបានទាមទារ។",
    "Password must be at least 6 characters.": "ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ។",
    "Passwords do not match.": "ពាក្យសម្ងាត់មិនត្រូវគ្នា។",
    "Failed to reset password. The code may be invalid or expired.": "ការកំណត់ពាក្យសម្ងាត់ឡើងវិញបរាជ័យ។ លេខកូដអាចមិនត្រឹមត្រូវ ឬផុតកំណត់។",

    // Settings
    "Account Settings": "ការកំណត់គណនី",
    "Enter phone number": "បញ្ចូលលេខទូរសព្ទ",
    "Address": "អាសយដ្ឋាន",
    "Enter address": "បញ្ចូលអាសយដ្ឋាន",
    "University Email": "អ៊ីមែលសាកលវិទ្យាល័យ",
    "Claim your official": "ទាមទារអ៊ីមែលផ្លូវការរបស់អ្នក",
    "email address.": "អាសយដ្ឋានអ៊ីមែល។",
    "Get University Email": "ទទួលអ៊ីមែលសាកលវិទ្យាល័យ",
    "Change Password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "Current Password": "ពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "Enter current password": "បញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "Confirm New Password": "បញ្ជាក់ពាក្យសម្ងាត់ថ្មី",
    "Save Changes": "រក្សាទុកការផ្លាស់ប្តូរ",
    "Changes saved successfully!": "ការផ្លាស់ប្តូរត្រូវបានរក្សាទុកដោយជោគជ័យ!",
    "Failed to save changes.": "ការរក្សាទុកការផ្លាស់ប្តូរបរាជ័យ។",
    "Server not reachable.": "មិនអាចភ្ជាប់ម៉ាស៊ីនមេ។",

    // Logout modal
    "Are you sure you want to logout?": "តើអ្នកប្រាកដថាចង់ចាកចេញទេ?",
    "Cancel": "បោះបង់",
    "Logging out...": "កំពុងចាកចេញ...",

    // Homepage / About / Slideshow / News
    "Cambodia": "កម្ពុជា",
    "International": "អន្តរជាតិ",
    "University": "សាកលវិទ្យាល័យ",
    "Building your dream with our University, and make a wish come true, taste more Experincce then you you had, more labs and over 1000 students achived their goal. Welcome to Cambodia International University.": "សាងសង់ក្តីសុបិនរបស់អ្នកជាមួយសាកលវិទ្យាល័យរបស់យើង ធ្វើឱ្យសេចក្តីប្រាថ្នាក្លាយជាការពិត ទទួលបានបទពិសោធន៍ច្រើនជាងមុន មានមន្ទីរពិសោធន៍ច្រើន ហើយសិស្សជាង ១០០០ នាក់បានសម្រេចគោលដៅរបស់ពួកគេ។ សូមស្វាគមន៍មកកាន់សាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា។",
    "Our Labs had over 200 for students to study in their dream": "មន្ទីរពិសោធន៍របស់យើងមានជាង ២០០ សម្រាប់សិស្សសិក្សាក្នុងក្តីសុបិនរបស់ពួកគេ",
    "Enroll now to match your skills": "ចុះឈ្មោះឥឡូវនេះ ដើម្បីផ្គូផ្គងជំនាញរបស់អ្នក",
    "View Course": "មើលវគ្គសិក្សា",
    "See More": "មើលបន្ថែម",
    "Content Slide Display Image": "រូបភាពបង្ហាញស្លាយមាតិកា",
    "Excellence in Education": "ឧត្តមភាពក្នុងការអប់រំ",
    "Shaping future leaders since 2005": "បណ្តុះអ្នកដឹកនាំអនាគតតាំងពីឆ្នាំ ២០០៥",
    "World-Class Campus": "បរិវេណសាលាកម្រិតពិភពលោក",
    "State-of-the-art facilities for modern learning": "បរិក្ខារទំនើបសម្រាប់ការសិក្សាសម័យទំនើប",
    "Global Community": "សហគមន៍សកល",
    "Students from over 50 countries": "សិស្សមកពីជាង ៥០ ប្រទេស",
    "Innovation Hub": "មជ្ឈមណ្ឌលច្នៃប្រឌិត",
    "Where ideas become reality": "កន្លែងដែលគំនិតក្លាយជាការពិត",
    "article": "អត្ថបទ",
    "articles": "អត្ថបទ",
    "By": "ដោយ",
    "Read more": "អានបន្ថែម",
    "About Cambodia International University": "អំពីសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា",
    "Empowering the next generation of leaders through quality education and innovation since 2005.": "ពង្រឹងអ្នកដឹកនាំជំនាន់ក្រោយតាមរយៈការអប់រំប្រកបដោយគុណភាព និងការច្នៃប្រឌិតតាំងពីឆ្នាំ ២០០៥។",
    "Empowering minds, shaping futures. Committed to excellence in education, research, and innovation since 2005.": "ពង្រឹងបញ្ញា រៀបចំអនាគត។ ប្តេជ្ញាចិត្តចំពោះឧត្តមភាពក្នុងការអប់រំ ការស្រាវជ្រាវ និងការច្នៃប្រឌិតតាំងពីឆ្នាំ ២០០៥។",
    "Our Mission": "បេសកកម្មរបស់យើង",
    "To provide accessible, affordable, and high-quality higher education that prepares students to become competent professionals and responsible citizens in a global society.": "ផ្តល់ការអប់រំឧត្តមសិក្សាដែលអាចចូលដំណើរការបាន តម្លៃសមរម្យ និងគុណភាពខ្ពស់ ដែលរៀបចំសិស្សឱ្យក្លាយជាអ្នកជំនាញមានសមត្ថភាព និងពលរដ្ឋល្អនៅក្នុងសង្គមសកល។",
    "Our Vision": "ចក្ខុវិស័យរបស់យើង",
    "To be a leading university in the region, recognized for academic excellence, research innovation, and community engagement.": "ធ្វើជាសាកលវិទ្យាល័យឈានមុខក្នុងតំបន់ ដែលត្រូវបានទទួលស្គាល់សម្រាប់ឧត្តមភាពសិក្សា ការច្នៃប្រឌិតស្រាវជ្រាវ និងការចូលរួមជាមួយសហគមន៍។",
    "Why Choose CIU?": "ហេតុអ្វីជ្រើសរើស CIU?",
    "Experienced Faculty": "គ្រូដែលមានបទពិសោធន៍",
    "Learn from industry experts and experienced professors.": "រៀនពីអ្នកជំនាញក្នុងឧស្សាហកម្ម និងសាស្ត្រាចារ្យដែលមានបទពិសោធន៍។",
    "Global Network": "បណ្តាញសកល",
    "Connect with students and partners worldwide.": "ភ្ជាប់ជាមួយសិស្ស និងដៃគូនៅទូទាំងពិភពលោក។",
    "Modern Facilities": "បរិក្ខារទំនើប",
    "State-of-the-art labs, libraries, and online resources.": "មន្ទីរពិសោធន៍ បណ្ណាល័យ និងធនធានអនឡាញទំនើប។",
    "Accredited Programs": "កម្មវិធីទទួលស្គាល់",
    "All programs are recognized by the Ministry of Education.": "កម្មវិធីទាំងអស់ត្រូវបានទទួលស្គាល់ដោយក្រសួងអប់រំ។",

    // Contact page
    "Failed to send message. Please try again.": "ការផ្ញើសារបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "All of responsibility is provide by us": "រាល់ទំនួលខុសត្រូវគឺផ្តល់ដោយយើង",
    "contact us for more information about our University.": "ទាក់ទងមកយើងសម្រាប់ព័ត៌មានបន្ថែមអំពីសាកលវិទ្យាល័យរបស់យើង។",
    "Contact us": "ទាក់ទងមកយើង",
    "Tell us your username*": "ប្រាប់យើងពីឈ្មោះអ្នកប្រើរបស់អ្នក*",
    "Please enter your username": "សូមបញ្ចូលឈ្មោះអ្នកប្រើរបស់អ្នក",
    "Tell us your Phone number*": "ប្រាប់យើងពីលេខទូរសព្ទរបស់អ្នក*",
    "Please enter your phone number": "សូមបញ្ចូលលេខទូរសព្ទរបស់អ្នក",
    "Tell us your email*": "ប្រាប់យើងពីអ៊ីមែលរបស់អ្នក*",
    "Please enter your email": "សូមបញ្ចូលអ៊ីមែលរបស់អ្នក",
    "Tell us about your message*": "ប្រាប់យើងអំពីសាររបស់អ្នក*",
    "Your message here...": "សាររបស់អ្នកនៅទីនេះ...",
    "Confirm": "បញ្ជាក់",
    "Error": "កំហុស",
    "Close": "បិទ",
    "Submit Successful": "ការដាក់ស្នើជោគជ័យ",
    "Your Application has been submit successfully": "ការដាក់ពាក្យរបស់អ្នកត្រូវបានដាក់ស្នើដោយជោគជ័យ",
    "you will received our email in 24h after": "អ្នកនឹងទទួលបានអ៊ីមែលរបស់យើងក្នុងរយៈពេល ២៤ ម៉ោងបន្ទាប់",
    "the application has been submit": "ការដាក់ពាក្យត្រូវបានដាក់ស្នើ",
    "Back to Home": "ត្រឡប់ទៅទំព័រដើម",
    "This contact provided by our University.": "ការទំនាក់ទំនងនេះផ្តល់ដោយសាកលវិទ្យាល័យរបស់យើង។",
    "Contact us for more information": "ទាក់ទងមកយើងសម្រាប់ព័ត៌មានបន្ថែម",
    "Developer System": "ប្រព័ន្ធអ្នកអភិវឌ្ឍន៍",
    "Github": "Github",

    // Enrollment form
    "Required": "តម្រូវឱ្យបំពេញ",
    "Must be 15–60": "ត្រូវមានអាយុ ១៥–៦០",
    "Submission failed. Please try again.": "ការដាក់ស្នើបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Server not reachable. Make sure the backend is running.": "មិនអាចភ្ជាប់ម៉ាស៊ីនមេ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Application for Enroll Class": "ពាក្យសុំចូលរៀន",
    "After you submit the application you will receive an email from our University within 24 hours.": "បន្ទាប់ពីអ្នកដាក់ស្នើពាក្យសុំ អ្នកនឹងទទួលបានអ៊ីមែលពីសាកលវិទ្យាល័យរបស់យើងក្នុងរយៈពេល ២៤ ម៉ោង។",
    "— Official Enrollment Application Form.": "— ទម្រង់ពាក្យសុំចុះឈ្មោះចូលរៀនផ្លូវការ។",
    "Please fill in all required fields marked with": "សូមបំពេញគ្រប់វាលដែលតម្រូវ ដែលសម្គាល់ដោយ",
    "Student Information": "ព័ត៌មានសិស្ស",
    "First Name (EN) *": "នាមខ្លួន (EN) *",
    "e.g. Sophea": "ឧ. សុភា",
    "Last Name (EN) *": "នាមត្រកូល (EN) *",
    "e.g. Chan": "ឧ. ចាន់",
    "First Name (KH)": "នាមខ្លួន (KH)",
    "Last Name (KH)": "នាមត្រកូល (KH)",
    "Age *": "អាយុ *",
    "e.g. 20": "ឧ. ២០",
    "Date of Birth *": "ថ្ងៃខែឆ្នាំកំណើត *",
    "Place of Birth *": "ទីកន្លែងកំណើត *",
    "City / Province": "ទីក្រុង / ខេត្ត",
    "Sex *": "ភេទ *",
    "Nationality *": "សញ្ជាតិ *",
    "Select nationality": "ជ្រើសរើសសញ្ជាតិ",
    "Phone Number *": "លេខទូរសព្ទ *",
    "Email Address *": "អាសយដ្ឋានអ៊ីមែល *",
    "Class Information": "ព័ត៌មានថ្នាក់",
    "Start Date *": "ថ្ងៃចាប់ផ្តើម *",
    "Select start date": "ជ្រើសរើសថ្ងៃចាប់ផ្តើម",
    "Major *": "ជំនាញ *",
    "Select major": "ជ្រើសរើសជំនាញ",
    "Year *": "ឆ្នាំ *",
    "Select year": "ជ្រើសរើសឆ្នាំ",
    "Degree *": "សញ្ញាបត្រ *",
    "Select degree": "ជ្រើសរើសសញ្ញាបត្រ",
    "Confirm & Submit →": "បញ្ជាក់ និងដាក់ស្នើ →",
    "Your application has been submitted successfully.": "ពាក្យសុំរបស់អ្នកត្រូវបានដាក់ស្នើដោយជោគជ័យ។",
    "You will receive our confirmation email within": "អ្នកនឹងទទួលបានអ៊ីមែលបញ្ជាក់របស់យើងក្នុងរយៈពេល",
    "Confirmation sent to:": "ការបញ្ជាក់ត្រូវបានផ្ញើទៅកាន់:",
    "your email": "អ៊ីមែលរបស់អ្នក",
    "Application Summary": "សង្ខេបពាក្យសុំ",
    "← Back to Home": "← ត្រឡប់ទៅទំព័រដើម",
    "This information provided by Cambodia International University": "ព័ត៌មាននេះផ្តល់ដោយសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា",
    "Name": "ឈ្មោះ",
    "Male": "ប្រុស",
    "Female": "ស្រី",
    "Computer Science": "វិទ្យាសាស្ត្រកុំព្យូទ័រ",
    "Business Administration": "គ្រប់គ្រងពាណិជ្ជកម្ម",
    "Engineering": "វិស្វកម្ម",
    "Medicine": "វេជ្ជសាស្ត្រ",
    "Law": "ច្បាប់",
    "Architecture": "ស្ថាបត្យកម្ម",
    "Education": "អប់រំ",
    "Arts & Design": "សិល្បៈ និងការរចនា",
    "Bachelor's Degree": "បរិញ្ញាបត្រ",
    "Master's Degree": "អនុបណ្ឌិត",
    "PhD": "បណ្ឌិត",
    "Associate Degree": "សញ្ញាបត្ររង",
    "Diploma": "សញ្ញាបត្រវិជ្ជាជីវៈ",
    "Year 1": "ឆ្នាំទី ១",
    "Year 2": "ឆ្នាំទី ២",
    "Year 3": "ឆ្នាំទី ៣",
    "Year 4": "ឆ្នាំទី ៤",
    "Year 5": "ឆ្នាំទី ៥",
    "September 2026": "ខែកញ្ញា ២០២៦",
    "January 2027": "ខែមករា ២០២៧",
    "March 2027": "ខែមីនា ២០២៧",
    "June 2027": "ខែមិថុនា ២០២៧",
    "Cambodian": "ខ្មែរ",
    "Vietnamese": "វៀតណាម",
    "Chinese": "ចិន",
    "Korean": "កូរ៉េ",
    "American": "អាមេរិក",
    "French": "បារាំង",
    "Other": "ផ្សេងៗ",
    "Application": "ពាក្យសុំ",
    "Confirmation": "ការបញ្ជាក់",
    "Success": "ជោគជ័យ",

    // Student email form
    "Student ID is required": "តម្រូវឱ្យបញ្ចូលលេខសម្គាល់សិស្ស",
    "Select your department": "ជ្រើសរើសផ្នែករបស់អ្នក",
    "Select your year": "ជ្រើសរើសឆ្នាំរបស់អ្នក",
    "No student record found.": "រកមិនឃើញកំណត់ត្រាសិស្ស។",
    "Backend not reachable. Make sure the server is running.": "មិនអាចភ្ជាប់ម៉ាស៊ីនមេ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Please log in first to claim your student email.": "សូមចូលគណនីជាមុន ដើម្បីទាមទារអ៊ីមែលសិស្សរបស់អ្នក។",
    "Go to Login": "ទៅកាន់ទំព័រចូល",
    "Email Generated!": "អ៊ីមែលត្រូវបានបង្កើត!",
    "Your student email has been created successfully.": "អ៊ីមែលសិស្សរបស់អ្នកត្រូវបានបង្កើតដោយជោគជ័យ។",
    "Your student email:": "អ៊ីមែលសិស្សរបស់អ្នក:",
    "Account Email:": "អ៊ីមែលគណនី:",
    "Student ID:": "លេខសម្គាល់សិស្ស:",
    "Department:": "ផ្នែក:",
    "Year:": "ឆ្នាំ:",
    "Claim Another": "ទាមទារមួយទៀត",
    "Claim Your Student Email": "ទាមទារអ៊ីមែលសិស្សរបស់អ្នក",
    "Verify your student identity to get a": "ផ្ទៀងផ្ទាត់អត្តសញ្ញាណសិស្សរបស់អ្នក ដើម្បីទទួលបាន",
    "email": "អ៊ីមែល",
    "Account Email": "អ៊ីមែលគណនី",
    "Student ID": "លេខសម្គាល់សិស្ស",
    "e.g. CS-2024-001": "ឧ. CS-2024-001",
    "Department": "ផ្នែក",
    "Select...": "ជ្រើសរើស...",
    "Year": "ឆ្នាំ",
    "Claim Email": "ទាមទារអ៊ីមែល",
    "Your email will be:": "អ៊ីមែលរបស់អ្នកនឹងមានៈ",
    "Information Technology": "បច្ចេកវិទ្យាព័ត៌មាន",
    "Business Management": "គ្រប់គ្រងពាណិជ្ជកម្ម",
    "Marketing": "ទីផ្សារ",
    "Accounting & Finance": "គណនេយ្យ និងហិរញ្ញវត្ថុ",
    "English Literature": "អក្សរសិល្ប៍អង់គ្លេស",

    // Footer
    "Cambodia International University": "សាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Instagram": "Instagram",
    "GitHub": "GitHub",
    "TikTok": "TikTok",
    "Telegram": "Telegram",
    "Quick Links": "តំណរហ័ស",
    "Facilities": "បរិក្ខារ",
    "Faculty & Staff": "សាស្ត្រាចារ្យ និងបុគ្គលិក",
    "Resources": "ធនធាន",
    "Library": "បណ្ណាល័យ",
    "Events": "ព្រឹត្តិការណ៍",
    "Stay Updated": "តាមដានព័ត៌មាន",
    "Subscribe to receive our digital announcements.": "ជាវដើម្បីទទួលការប្រកាសឌីជីថលរបស់យើង។",
    "Your email": "អ៊ីមែលរបស់អ្នក",
    "Join": "ចូលរួម",
    "Phnom Penh, Cambodia": "ភ្នំពេញ កម្ពុជា",
    "Cambodia International University. All rights reserved.": "សាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា។ រក្សាសិទ្ធិគ្រប់យ៉ាង។",
    "Terms of Service": "លក្ខខណ្ឌនៃការប្រើប្រាស់",
    "Sitemap": "ផែនទីគេហទំព័រ",
    "This contact provided by our University.": "ការទំនាក់ទំនងនេះផ្តល់ដោយសាកលវិទ្យាល័យរបស់យើង។",

    // Public info pages
    "Frequently Asked Questions": "សំណួរដែលគេសួរញឹកញាប់",
    "Find quick answers to the most common questions from students and parents.": "ស្វែងរកចម្លើយរហ័សចំពោះសំណួរទូទៅបំផុតពីសិស្ស និងឪពុកម្តាយ។",
    "How do I apply for admission?": "តើខ្ញុំដាក់ពាក្យសុំចូលរៀនដោយរបៀបណា?",
    "Click the 'Enroll' button in the navigation bar, fill out the online application form, and submit it. Our admissions team will contact you within a few business days.": "ចុចប៊ូតុង 'Enroll' នៅក្នុងរបារនាវាចរ បំពេញទម្រង់ពាក្យសុំតាមអនឡាញ ហើយដាក់ស្នើ។ ក្រុមការងារទទួលចូលរៀនរបស់យើងនឹងទាក់ទងអ្នកក្នុងរយៈពេលពីរបីថ្ងៃធ្វើការ។",
    "What documents do I need for enrollment?": "តើឯកសារអ្វីខ្លះដែលខ្ញុំត្រូវការសម្រាប់ការចុះឈ្មោះ?",
    "You'll need your national ID or passport, high school diploma (or equivalent), recent photos, and proof of payment for the registration fee.": "អ្នកត្រូវការអត្តសញ្ញាណប័ណ្ណ ឬលិខិតឆ្លងដែន សញ្ញាបត្រវិទ្យាល័យ (ឬសមមូល) រូបថតថ្មីៗ និងភស្តុតាងនៃការទូទាត់ថ្លៃចុះឈ្មោះ។",
    "How can I claim my student email?": "តើខ្ញុំអាចទាមទារអ៊ីមែលសិស្សរបស់ខ្ញុំដោយរបៀបណា?",
    "Use the 'Claim Student Email' form available on the homepage. Enter your details and you'll receive your official university email address.": "ប្រើប្រាស់ទម្រង់ 'Claim Student Email' ដែលមាននៅលើទំព័រដើម។ បញ្ចូលព័ត៌មានរបស់អ្នក ហើយអ្នកនឹងទទួលបានអាសយដ្ឋានអ៊ីមែលសាកលវិទ្យាល័យផ្លូវការ។",
    "How do I pay my tuition fees?": "តើខ្ញុំបង់ថ្លៃសិក្សារបស់ខ្ញុំដោយរបៀបណា?",
    "Go to the Payments page, scan the QR code with your banking app, and submit the payment form with your student ID and amount.": "ទៅកាន់ទំព័រទូទាត់ប្រាក់ ស្កេនកូដ QR ជាមួយកម្មវិធីធនាគាររបស់អ្នក ហើយដាក់ស្នើទម្រង់ទូទាត់ជាមួយលេខសម្គាល់សិស្ស និងចំនួនទឹកប្រាក់របស់អ្នក។",
    "Can I change my enrolled course?": "តើខ្ញុំអាចប្តូរវគ្គសិក្សាដែលបានចុះឈ្មោះបានទេ?",
    "Yes, you can request a course change by contacting the registrar's office or by speaking with your academic advisor during the add/drop period.": "បាទ អ្នកអាចស្នើសុំប្តូរវគ្គសិក្សាដោយទាក់ទងការិយាល័យចុះឈ្មោះ ឬនិយាយជាមួយទីប្រឹក្សាសិក្សារបស់អ្នកក្នុងអំឡុងពេលបន្ថែម/ដកវគ្គ។",
    "How do I access my grades?": "តើខ្ញុំចូលមើលពិន្ទុរបស់ខ្ញុំដោយរបៀបណា?",
    "Log into the Student Portal with your student account and open the 'Grades' section to view your scores and transcripts.": "ចូលទៅកាន់វិបផតថលសិស្សជាមួយគណនីសិស្សរបស់អ្នក ហើយបើកផ្នែក 'Grades' ដើម្បីមើលពិន្ទុ និងប្រវត្តិរូបសិក្សារបស់អ្នក។",
    "Does the university offer scholarships?": "តើសាកលវិទ្យាល័យផ្តល់អាហារូបករណ៍ដែរឬទេ?",
    "Yes. Visit the Scholarships page to learn about merit-based and need-based scholarships available to qualified students.": "បាទ។ សូមចូលមើលទំព័រអាហារូបករណ៍ ដើម្បីស្វែងយល់អំពីអាហារូបករណ៍ផ្អែកលើសមត្ថភាព និងតម្រូវការ ដែលមានសម្រាប់សិស្សដែលមានលក្ខណៈសម្បត្តិគ្រប់គ្រាន់។",
    "Academic Calendar": "ប្រតិទិនសិក្សា",
    "Key dates and events for the 2026–2027 academic year.": "កាលបរិច្ឆេទ និងព្រឹត្តិការណ៍សំខាន់ៗសម្រាប់ឆ្នាំសិក្សា ២០២៦–២០២៧។",
    "Registration Opens": "បើកការចុះឈ្មោះ",
    "Online registration opens for the new academic year.": "ការចុះឈ្មោះតាមអនឡាញបើកសម្រាប់ឆ្នាំសិក្សាថ្មី។",
    "Orientation Week": "សប្តាហ៍ណែនាំ",
    "Welcome event for new students across all faculties.": "ព្រឹត្តិការណ៍ស្វាគមន៍សិស្សថ្មីនៅទូទាំងមហាវិទ្យាល័យទាំងអស់។",
    "First Day of Classes": "ថ្ងៃដំបូងនៃការចាប់ផ្តើមថ្នាក់",
    "Semester 1 lectures begin.": "ថ្នាក់រៀនឆមាសទី ១ ចាប់ផ្តើម។",
    "Midterm Examinations": "ការប្រឡងពាក់កណ្តាលឆមាស",
    "Midterm exams run for one week.": "ការប្រឡងពាក់កណ្តាលឆមាសធ្វើឡើងរយៈពេលមួយសប្តាហ៍។",
    "University Open Day": "ថ្ងៃបើកទ្វារសាកលវិទ្យាល័យ",
    "Campus tours and program showcases for prospective students.": "ដំណើរទស្សនាបរិវេណសាលា និងការបង្ហាញកម្មវិធីសម្រាប់សិស្សដែលមានបំណងចូលរៀន។",
    "Final Examinations": "ការប្រឡងចុងឆមាស",
    "Final exams for Semester 1.": "ការប្រឡងចុងឆមាសទី ១។",
    "Semester Break Begins": "ការឈប់សម្រាកឆមាសចាប់ផ្តើម",
    "Winter break starts after exams.": "ការឈប់សម្រាករដូវរងាចាប់ផ្តើមបន្ទាប់ពីការប្រឡង។",
    "Semester 2 Begins": "ឆមាសទី ២ ចាប់ផ្តើម",
    "Lectures resume for the second semester.": "ថ្នាក់រៀនបន្តសម្រាប់ឆមាសទី ២។",
    "Admission": "ការចូលរៀន",
    "Campus": "បរិវេណសាលា",
    "Academic": "សិក្សា",
    "Exam": "ការប្រឡង",
    "Holiday": "ថ្ងៃឈប់សម្រាក",
    "Scholarships": "អាហារូបករណ៍",
    "We believe talent and hard work should never be blocked by financial barriers.": "យើងជឿថា ទេពកោសល្យ និងការខិតខំមិនគួរត្រូវបានរារាំងដោយឧបសគ្គផ្នែកហិរញ្ញវត្ថុឡើយ។",
    "Merit Scholarship": "អាហារូបករណ៍សមត្ថភាព",
    "Awarded to students with outstanding academic performance in their final year of high school.": "ផ្តល់ជូនសិស្សដែលមានលទ្ធផលសិក្សាពូកែក្នុងឆ្នាំចុងក្រោយនៃវិទ្យាល័យ។",
    "Up to 100% tuition": "ថ្លៃសិក្សារហូតដល់ ១០០%",
    "Top 5% of graduating class": "ស្ថិតក្នុង ៥% កំពូលនៃថ្នាក់បញ្ចប់ការសិក្សា",
    "Minimum GPA 3.6": "ពិន្ទុ GPA អប្បបរមា ៣.៦",
    "Pass entrance interview": "ប្រឡងជាប់ការសម្ភាសន៍ចូលរៀន",
    "Need-Based Scholarship": "អាហារូបករណ៍ផ្អែកលើតម្រូវការ",
    "Financial support for talented students facing economic hardship.": "ការគាំទ្រផ្នែកហិរញ្ញវត្ថុសម្រាប់សិស្សពូកែដែលប្រឈមនឹងការលំបាកផ្នែកសេដ្ឋកិច្ច។",
    "50% tuition + allowance": "ថ្លៃសិក្សា ៥០% + ប្រាក់ឧបត្ថម្ភ",
    "Proof of financial need": "ភស្តុតាងនៃតម្រូវការផ្នែកហិរញ្ញវត្ថុ",
    "Minimum GPA 3.0": "ពិន្ទុ GPA អប្បបរមា ៣.០",
    "Recommendation letter": "លិខិតអនុសាសន៍",
    "Sports Scholarship": "អាហារូបករណ៍កីឡា",
    "For student-athletes representing the university in national competitions.": "សម្រាប់សិស្សកីឡាករដែលតំណាងសាកលវិទ្យាល័យក្នុងការប្រកួតថ្នាក់ជាតិ។",
    "Up to 70% tuition": "ថ្លៃសិក្សារហូតដល់ ៧០%",
    "National-level achievement": "សមិទ្ធផលកម្រិតជាតិ",
    "Minimum GPA 2.8": "ពិន្ទុ GPA អប្បបរមា ២.៨",
    "Trial performance": "ការសម្តែងសាកល្បង",
    "Women in STEM Scholarship": "អាហារូបករណ៍ស្ត្រីក្នុងវិស័យ STEM",
    "Encouraging female students to pursue science, technology, engineering and mathematics.": "លើកទឹកចិត្តសិស្សានុសិស្សស្រីឱ្យបន្តវិស័យវិទ្យាសាស្ត្រ បច្ចេកវិទ្យា វិស្វកម្ម និងគណិតវិទ្យា។",
    "60% tuition": "ថ្លៃសិក្សា ៦០%",
    "Female applicant": "អ្នកដាក់ពាក្យភេទស្រី",
    "STEM program enrollment": "ការចុះឈ្មោះកម្មវិធី STEM",
    "Minimum GPA 3.2": "ពិន្ទុ GPA អប្បបរមា ៣.២",
    "Sibling Scholarship": "អាហារូបករណ៍បងប្អូនបង្កើត",
    "Discount for families with two or more siblings enrolled at CIU.": "ការបញ្ចុះតម្លៃសម្រាប់គ្រួសារដែលមានបងប្អូនពីរនាក់ ឬច្រើននាក់បានចុះឈ្មោះនៅ CIU។",
    "20% tuition per sibling": "ថ្លៃសិក្សា ២០% ក្នុងមួយនាក់",
    "Sibling already enrolled": "បងប្អូនបានចុះឈ្មោះរួចហើយ",
    "Minimum GPA 2.5": "ពិន្ទុ GPA អប្បបរមា ២.៥",
    " page and mention the scholarship you're applying for in the notes. The scholarship committee reviews applications twice a year.": " ហើយបញ្ជាក់អាហារូបករណ៍ដែលអ្នកកំពុងដាក់ពាក្យនៅក្នុងចំណាំ។ គណៈកម្មាធិការអាហារូបករណ៍ពិនិត្យពាក្យសុំពីរដងក្នុងមួយឆ្នាំ។",
    "To apply for a scholarship, submit your application through the ": "ដើម្បីដាក់ពាក្យសុំអាហារូបករណ៍ សូមដាក់ស្នើពាក្យសុំរបស់អ្នកតាមរយៈទំព័រ",
    "Campus Facilities": "បរិក្ខារបរិវេណសាលា",
    "Everything you need to learn, create, and grow — all on one campus.": "អ្វីគ្រប់យ៉ាងដែលអ្នកត្រូវការដើម្បីរៀន បង្កើត និងរីកចម្រើន — ទាំងអស់នៅលើបរិវេណសាលាតែមួយ។",
    "Modern Library": "បណ្ណាល័យទំនើប",
    "A five-floor library with over 200,000 books, quiet study zones, group rooms, and a digital resource center open from 7am to 9pm.": "បណ្ណាល័យប្រាំជាន់ ដែលមានសៀវភៅជាង ២០០,០០០ ក្បាល តំបន់សិក្សាស្ងាត់ បន្ទប់ជាក្រុម និងមជ្ឈមណ្ឌលធនធានឌីជីថល បើកពីម៉ោង ៧ ព្រឹក ដល់ ៩ យប់។",
    "Computer Labs": "បន្ទប់កុំព្យូទ័រ",
    "24/7 access labs equipped with high-performance machines and industry-standard software for programming and design students.": "បន្ទប់កុំព្យូទ័រចូលប្រើ ២៤/៧ បំពាក់ដោយម៉ាស៊ីនមានប្រសិទ្ធភាពខ្ពស់ និងកម្មវិធីស្តង់ដារឧស្សាហកម្មសម្រាប់សិស្សផ្នែកកម្មវិធី និងការរចនា។",
    "Science Laboratories": "មន្ទីរពិសោធន៍វិទ្យាសាស្ត្រ",
    "Fully equipped physics, chemistry, and biology labs with modern safety standards for hands-on learning.": "មន្ទីរពិសោធន៍រូបវិទ្យា គីមីវិទ្យា និងជីវវិទ្យាពេញលេញ ជាមួយស្តង់ដារសុវត្ថិភាពទំនើបសម្រាប់ការសិក្សាអនុវត្តជាក់ស្តែង។",
    "Sports Complex": "មជ្ឈមណ្ឌលកីឡា",
    "An indoor gym, football field, basketball courts, and swimming pool available to all students and staff.": "កន្លែងហាត់ប្រាណក្នុងផ្ទះ ទីលានបាល់ទាត់ ទីលានបាល់បោះ និងអាងហែលទឹក ដែលមានសម្រាប់សិស្ស និងបុគ្គលិកទាំងអស់។",
    "Student Center": "មជ្ឈមណ្ឌលសិស្ស",
    "A vibrant hub with cafeterias, lounge areas, meeting rooms, and space for student clubs and events.": "មជ្ឈមណ្ឌលដ៏រស់រវល់ ជាមួយកន្លែងលក់អាហារ កន្លែងសម្រាក បន្ទប់ប្រជុំ និងកន្លែងសម្រាប់ក្លឹបសិស្ស និងព្រឹត្តិការណ៍នានា។",
    "Wi-Fi Everywhere": "Wi-Fi គ្រប់ទីកន្លែង",
    "High-speed campus-wide Wi-Fi with secure access for students and faculty in every building and dormitory.": "Wi-Fi ល្បឿនលឿនគ្របដណ្តប់បរិវេណសាលា ជាមួយការចូលប្រើប្រកបដោយសុវត្ថិភាពសម្រាប់សិស្ស និងសាស្ត្រាចារ្យនៅក្នុងអគារ និងអន្តេវាសិកដ្ឋាននីមួយៗ។",
    "Our Faculty & Staff": "សាស្ត្រាចារ្យ និងបុគ្គលិករបស់យើង",
    "Meet the dedicated team supporting teaching, research, and student life at CIU.": "ស្គាល់ក្រុមការងារដ៏លះបង់ ដែលគាំទ្រការបង្រៀន ការស្រាវជ្រាវ និងជីវិតសិស្សនៅ CIU។",
    "Dr. Chan Dara": "បណ្ឌិត ចាន់ ដារ៉ា",
    "Rector": "សាកលវិទ្យាធិការ",
    "Executive Office": "ការិយាល័យប្រតិបត្តិ",
    "Prof. Sok Veasna": "សាស្ត្រាចារ្យ សុខ វាសនា",
    "Dean of Faculty of Science": "ព្រឹទ្ធបុរសមហាវិទ្យាល័យវិទ្យាសាស្ត្រ",
    "Faculty of Science": "មហាវិទ្យាល័យវិទ្យាសាស្ត្រ",
    "Dr. Chea Maly": "បណ្ឌិត ជា ម៉ាលី",
    "Dean of Faculty of Business": "ព្រឹទ្ធបុរសមហាវិទ្យាល័យពាណិជ្ជកម្ម",
    "Faculty of Business": "មហាវិទ្យាល័យពាណិជ្ជកម្ម",
    "Prof. Nop Piseth": "សាស្ត្រាចារ្យ ណុប ពីសេត",
    "Dean of Faculty of Engineering": "ព្រឹទ្ធបុរសមហាវិទ្យាល័យវិស្វកម្ម",
    "Faculty of Engineering": "មហាវិទ្យាល័យវិស្វកម្ម",
    "Dr. Kim Sreyneang": "បណ្ឌិត គឹម ស្រីនាង",
    "Registrar": "អ្នកកាន់បញ្ជី",
    "Academic Affairs": "កិច្ចការសិក្សា",
    "Mr. Hun Rithy": "លោក ហ៊ុន រិទ្ធី",
    "Head of IT Department": "ប្រធានដេប៉ាតឺម៉ង់ IT",
    "Information Technology": "បច្ចេកវិទ្យាព័ត៌មាន",
    "Ms. Ly Sokha": "កញ្ញា លី សុខា",
    "Student Affairs Officer": "មន្ត្រីកិច្ចការសិស្ស",
    "Student Services": "សេវាសិស្ស",
    "Mr. Prak Vireak": "លោក ប្រាក់ វីរៈ",
    "Librarian": "បណ្ណារក្ស",
    "University Library": "បណ្ណាល័យសាកលវិទ្យាល័យ",

    // Course / News detail
    "Back to Courses": "ត្រឡប់ទៅវគ្គសិក្សា",
    "Course not found": "រកមិនឃើញវគ្គសិក្សា",
    "The course you're looking for doesn't exist or may have been removed.": "វគ្គសិក្សាដែលអ្នកកំពុងស្វែងរកមិនមាន ឬអាចត្រូវបានដកចេញ។",
    "Browse Courses": "រកមើលវគ្គសិក្សា",
    "An in-depth program offered at Cambodia International University.": "កម្មវិធីស៊ីជម្រៅដែលផ្តល់ជូននៅសាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា។",
    "Code": "លេខកូដ",
    "Instructor": "គ្រូបង្រៀន",
    "TBA": "TBA",
    "Credits": "ក្រេឌីត",
    "credits": "ក្រេឌីត",
    "Duration": "រយៈពេល",
    "1 semester": "១ ឆមាស",
    "Course Overview": "ទិដ្ឋភាពទូទៅនៃវគ្គសិក្សា",
    "This course provides students with foundational and advanced knowledge in the subject area. Through lectures, practical sessions, and assessments, students will develop the skills needed to excel in their field.": "វគ្គសិក្សានេះផ្តល់ឱ្យសិស្សនូវចំណេះដឹងមូលដ្ឋាន និងកម្រិតខ្ពស់ក្នុងមុខវិជ្ជានេះ។ តាមរយៈការបង្រៀន វគ្គអនុវត្ត និងការវាយតម្លៃ សិស្សនឹងអភិវឌ្ឍជំនាញចាំបាច់ដើម្បីពូកែក្នុងវិស័យរបស់ពួកគេ។",
    "What You Will Learn": "អ្វីដែលអ្នកនឹងរៀន",
    "Core concepts and principles of the subject": "គោលគំនិត និងគោលការណ៍ស្នូលនៃមុខវិជ្ជា",
    "Hands-on practical skills and real-world applications": "ជំនាញអនុវត្តជាក់ស្តែង និងកម្មវិធីក្នុងពិភពពិត",
    "Critical thinking and problem-solving techniques": "ការគិតប្រកបដោយភាពវៃឆ្លាត និងបច្ចេកទេសដោះស្រាយបញ្ហា",
    "Teamwork and professional communication": "ការធ្វើការជាក្រុម និងការទំនាក់ទំនងប្រកបដោយវិជ្ជាជីវៈ",
    "Enroll in this Course": "ចុះឈ្មោះក្នុងវគ្គសិក្សានេះ",
    "Article not found": "រកមិនឃើញអត្ថបទ",
    "This article doesn't exist or may have been removed.": "អត្ថបទនេះមិនមាន ឬអាចត្រូវបានដកចេញ។",
    "Share": "ចែករំលែក",

    // Payment
    "Secure Payment Portal": "វិបផតថលទូទាត់ប្រាក់ប្រកបដោយសុវត្ថិភាព",
    "Make a Payment": "ធ្វើការទូទាត់ប្រាក់",
    "Scan the QR code to pay, then submit the form below": "ស្កេនកូដ QR ដើម្បីបង់ប្រាក់ រួចដាក់ស្នើទម្រង់ខាងក្រោម",
    "Scan & Pay": "ស្កេន និងបង់ប្រាក់",
    "Use any banking app to scan the QR code and send your payment.": "ប្រើប្រាស់កម្មវិធីធនាគារណាមួយដើម្បីស្កេនកូដ QR ហើយផ្ញើការទូទាត់របស់អ្នក។",
    "Enter the payment details exactly as shown on the form.": "បញ្ចូលព័ត៌មានលម្អិតនៃការទូទាត់ឱ្យចំដូចដែលបង្ហាញក្នុងទម្រង់។",
    "Payment QR Code": "កូដ QR សម្រាប់ទូទាត់",
    "Bank Account": "គណនីធនាគារ",
    "Account No.": "លេខគណនី",
    "Scan the QR code with your banking app": "ស្កេនកូដ QR ជាមួយកម្មវិធីធនាគាររបស់អ្នក",
    "Enter the exact amount and complete the transfer": "បញ្ចូលចំនួនទឹកប្រាក់ឱ្យចំ ហើយបញ្ចប់ការផ្ទេរ",
    "Submit the form with your payment details": "ដាក់ស្នើទម្រង់ជាមួយព័ត៌មានលម្អិតនៃការទូទាត់របស់អ្នក",
    "Logged in as": "បានចូលជា",
    "Amount (US$)": "ចំនួនទឹកប្រាក់ (US$)",
    "Date": "កាលបរិច្ឆេទ",
    "Payment Type": "ប្រភេទនៃការទូទាត់",
    "Select a payment type": "ជ្រើសរើសប្រភេទនៃការទូទាត់",
    "Processing...": "កំពុងដំណើរការ...",
    "Submit Payment": "ដាក់ស្នើការទូទាត់",
    "Cambodia International University — Payment Portal": "សាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា — វិបផតថលទូទាត់ប្រាក់",
    "Processing payment...": "កំពុងដំណើរការការទូទាត់...",
    "Please fill the Student ID": "សូមបំពេញលេខសម្គាល់សិស្ស",
    "Please fill the Amount": "សូមបំពេញចំនួនទឹកប្រាក់",
    "Please select a Date": "សូមជ្រើសរើសកាលបរិច្ឆេទ",
    "Please select a Payment Type": "សូមជ្រើសរើសប្រភេទនៃការទូទាត់",
    "Failed to record payment": "ការកត់ត្រាការទូទាត់បរាជ័យ",

    // Student dashboard
    "Student Portal": "វិបផតថលសិស្ស",
    "CIU Student Dashboard": "ផ្ទាំងគ្រប់គ្រងសិស្ស CIU",
    "Visit Public Page": "ចូលមើលទំព័រសាធារណៈ",
    "Enrolled Courses": "វគ្គសិក្សាដែលបានចុះឈ្មោះ",
    "Currently active enrollments": "ការចុះឈ្មោះសកម្មបច្ចុប្បន្ន",
    "Average Score": "ពិន្ទុមធ្យម",
    "Across": "នៅទូទាំង",
    "graded subject(s)": "មុខវិជ្ជាដែលបានដាក់ពិន្ទុ",
    "Program": "កម្មវិធី",
    "Quick Actions": "សកម្មភាពរហ័ស",
    "Enroll in a course": "ចុះឈ្មោះក្នុងវគ្គមួយ",
    "Enroll in a Course": "ចុះឈ្មោះក្នុងវគ្គមួយ",
    "Enroll using the course code provided by your faculty.": "ចុះឈ្មោះដោយប្រើលេខកូដវគ្គដែលផ្តល់ដោយមហាវិទ្យាល័យរបស់អ្នក។",
    "Enroll in Course": "ចុះឈ្មោះក្នុងវគ្គ",
    "Enrolled course": "វគ្គដែលបានចុះឈ្មោះ",
    "My Courses": "វគ្គសិក្សារបស់ខ្ញុំ",
    "You are not enrolled in any courses yet. Click \"Enroll in Course\" to get started.": "អ្នកមិនទាន់បានចុះឈ្មោះក្នុងវគ្គណាមួយនៅឡើយទេ។ ចុច \"Enroll in Course\" ដើម្បីចាប់ផ្តើម។",
    "Grades": "ពិន្ទុ",
    "Score": "ពិន្ទុ",
    "Grade": "ថ្នាក់",
    "No grades available yet.": "មិនទាន់មានពិន្ទុនៅឡើយទេ។",
    "Academic Transcript": "ប្រវត្តិរូបសិក្សា",
    "Grade Points": "ពិន្ទុសរុប",
    "Cumulative GPA": "GPA សរុប",
    "Credits Earned": "ក្រេឌីតដែលទទួលបាន",
    "Courses Completed": "វគ្គដែលបានបញ្ចប់",
    "No transcript data available yet.": "មិនទាន់មានទិន្នន័យប្រវត្តិរូបសិក្សានៅឡើយទេ។",
    "Payment History": "ប្រវត្តិនៃការទូទាត់",
    "Receipt": "បង្កាន់ដៃ",
    "Type": "ប្រភេទ",
    "Amount": "ចំនួនទឹកប្រាក់",
    "Official Payment Receipt": "បង្កាន់ដៃទូទាត់ផ្លូវការ",
    "Receipt No.": "លេខបង្កាន់ដៃ",
    "Status": "ស្ថានភាព",
    "Paid": "បានបង់",
    "Print": "បោះពុម្ព",
    "No payments recorded yet. Click \"Make a Payment\" to get started.": "មិនទាន់មានកំណត់ត្រាការទូទាត់នៅឡើយទេ។ ចុច \"Make a Payment\" ដើម្បីចាប់ផ្តើម។",
    "No Payment": "មិនទាន់មានការទូទាត់",
    "Retry": "ព្យាយាមម្តងទៀត",
    "Failed to load student records. Make sure the backend server is running.": "ការទាញយកទិន្នន័យបញ្ជីសិស្សបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "My Profile": "ប្រវត្តិរូបរបស់ខ្ញុំ",
    "Profile updated successfully.": "ប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។",
    "Major": "ជំនាញ",
    "e.g. Computer Science": "ឧ. វិទ្យាសាស្ត្រកុំព្យូទ័រ",
    "e.g. Year 2": "ឧ. ឆ្នាំទី ២",
    "Your current address": "អាសយដ្ឋានបច្ចុប្បន្នរបស់អ្នក",
    "Course code": "លេខកូដវគ្គ",
    "e.g. CS101": "ឧ. CS101",
    "Enrolling...": "កំពុងចុះឈ្មោះ...",
    "Enrolled in course": "បានចុះឈ្មោះក្នុងវគ្គ",
    "successfully.": "ដោយជោគជ័យ។",
    "Failed to enroll. Make sure the course code is valid.": "ការចុះឈ្មោះបរាជ័យ។ សូមប្រាកដថាលេខកូដវគ្គត្រឹមត្រូវ។",
    "Failed to load student data. Make sure the backend server is running.": "ការទាញយកទិន្នន័យសិស្សបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "General": "ទូទៅ",
    "Academic": "សិក្សា",
    "Financial": "ហិរញ្ញវត្ថុ",
    "Overview": "ទិដ្ឋភាពទូទៅ",
    "Announcements": "ការប្រកាស",
    "Midterm exam schedule is out": "កាលវិភាគប្រឡងពាក់កណ្តាលឆមាសបានចេញហើយ",
    "Midterm exams run October 24-30. Please check the Academic Calendar for your assigned rooms.": "ការប្រឡងពាក់កណ្តាលឆមាសធ្វើឡើងពីថ្ងៃទី ២៤-៣០ ខែតុលា។ សូមពិនិត្យប្រតិទិនសិក្សាសម្រាប់បន្ទប់របស់អ្នក។",
    "Library renovation postponed to next month": "ការជួសជុលបណ្ណាល័យត្រូវបានពន្យារពេលទៅខែក្រោយ",
    "The library will remain open during renovations. Please follow the temporary signage.": "បណ្ណាល័យនឹងបន្តបើកក្នុងអំឡុងពេលជួសជុល។ សូមអនុវត្តតាមផ្លាកសញ្ញាបណ្តោះអាសន្ន។",
    "Scholarship applications due Friday": "ការដាក់ពាក្យសុំអាហារូបករណ៍ផុតកំណត់ថ្ងៃសុក្រ",
    "Submit your merit scholarship application before 5 PM this Friday.": "ដាក់ស្នើពាក្យសុំអាហារូបករណ៍សមត្ថភាពរបស់អ្នកមុនម៉ោង ៥ ល្ងាចថ្ងៃសុក្រនេះ។",

    // Teacher dashboard
    "Teacher Portal": "វិបផតថលគ្រូ",
    "Cambodia Int'l University": "សាកលវិទ្យាល័យអន្តរជាតិកម្ពុជា",
    "Teacher Dashboard": "ផ្ទាំងគ្រប់គ្រងគ្រូ",
    "Student Dashboard": "ផ្ទាំងគ្រប់គ្រងសិស្ស",
    "Signed in as": "បានចូលជា",
    "Attendance saved for the selected students.": "វត្តមានត្រូវបានរក្សាទុកសម្រាប់សិស្សដែលបានជ្រើសរើស។",
    "My Classes": "ថ្នាក់របស់ខ្ញុំ",
    "Students": "សិស្ស",
    "Attendance": "វត្តមាន",
    "Grade Entry": "ការបញ្ចូលពិន្ទុ",
    "Active this semester": "សកម្មក្នុងឆមាសនេះ",
    "Across all classes": "នៅទូទាំងថ្នាក់ទាំងអស់",
    "Avg Attendance": "វត្តមានមធ្យម",
    "This week": "សប្តាហ៍នេះ",
    "Pending Grades": "ពិន្ទុដែលកំពុងរង់ចាំ",
    "All submitted": "បានដាក់ស្នើទាំងអស់",
    "Today's Schedule": "កាលវិភាគថ្ងៃនេះ",
    "students": "សិស្ស",
    "Recent Announcements": "ការប្រកាសថ្មីៗ",
    "New Class": "ថ្នាក់ថ្មី",
    "Title": "ចំណងជើង",
    "Schedule": "កាលវិភាគ",
    "Student Roster": "បញ្ជីសិស្ស",
    "Search students...": "ស្វែងរកសិស្ស...",
    "ID": "លេខសម្គាល់",
    "Major": "ជំនាញ",
    "No students found": "រកមិនឃើញសិស្ស",
    "No students match your search.": "រកមិនឃើញសិស្សដែលត្រូវនឹងការស្វែងរករបស់អ្នក។",
    "Take Attendance": "កត់ត្រាវត្តមាន",
    "Save Attendance": "រក្សាទុកវត្តមាន",
    "Mark": "សម្គាល់",
    "Absent": "អវត្តមាន",
    "Present": "វត្តមាន",
    "Not marked": "មិនបានសម្គាល់",
    "Mark Present": "សម្គាល់វត្តមាន",
    "Mark Absent": "សម្គាល់អវត្តមាន",
    "Submit Grades": "ដាក់ស្នើពិន្ទុ",
    "Class": "ថ្នាក់",
    "0 - 100": "០ - ១០០",
    "Post Announcement": "ប្រកាសការប្រកាស",
    "Introduction to Programming": "សេចក្តីផ្តើមកម្មវិធីកុំព្យូទ័រ",
    "Data Structures": "រចនាសម្ព័ន្ធទិន្នន័យ",
    "Database Systems": "ប្រព័ន្ធគ្រប់គ្រងទិន្នន័យ",
    "Mon & Wed 08:00-09:30": "ចន្ទ និងពុធ ០៨:០០-០៩:៣០",
    "Tue & Thu 10:00-11:30": "អង្គារ និងព្រហស្បតិ៍ ១០:០០-១១:៣០",
    "Fri 14:00-17:00": "សុក្រ ១៤:០០-១៧:០០",
    "Software Engineering": "វិស្វកម្មសូហ្វវែរ",
    "Data Science": "វិទ្យាសាស្ត្រទិន្នន័យ",
    "Faculty meeting — Friday": "ការប្រជុំសាស្ត្រាចារ្យ — ថ្ងៃសុក្រ",
    "All faculty must attend the monthly meeting in Room A201 at 15:00.": "សាស្ត្រាចារ្យទាំងអស់ត្រូវចូលរួមការប្រជុំប្រចាំខែនៅបន្ទប់ A201 វេលាម៉ោង ១៥:០០។",
    "New grading policy": "គោលការណ៍ថ្មីនៃការវាយតម្លៃ",
    "Please review the updated grading policy document on the faculty portal.": "សូមពិនិត្យឯកសារគោលការណ៍ថ្មីនៃការវាយតម្លៃនៅលើវិបផតថលសាស្ត្រាចារ្យ។",

    // Admin dashboard
    "Setting": "ការកំណត់",
    "Amount Income": "ចំនួនប្រាក់ចំណូល",
    "Attendances": "វត្តមាន",
    "Student Attendance": "វត្តមានសិស្ស",
    "Teacher Attendance": "វត្តមានគ្រូ",
    "About Students": "អំពីសិស្ស",
    "Schedule": "កាលវិភាគ",
    "Report": "របាយការណ៍",
    "Account": "គណនី",
    "Student Account": "គណនីសិស្ស",
    "Teacher Account": "គណនីគ្រូ",
    "Admin Account": "គណនីអ្នកគ្រប់គ្រង",
    "User Management": "ការគ្រប់គ្រងអ្នកប្រើ",
    "Management": "ការគ្រប់គ្រង",
    "Courses": "វគ្គសិក្សា",
    "News": "ព័ត៌មាន",
    "Enrollments": "ការចុះឈ្មោះ",
    "Contact Inbox": "ប្រអប់ទំនាក់ទំនង",
    "Audit Log": "កំណត់ហេតុសវនកម្ម",
    "Username:": "ឈ្មោះអ្នកប្រើ:",
    "ID:": "លេខសម្គាល់:",
    "Major:": "ជំនាញ:",
    "Class:": "ថ្នាក់:",
    "Attendance:": "វត្តមាន:",
    "Absent:": "អវត្តមាន:",
    "On Date:": "នៅថ្ងៃ:",
    "Year:": "ឆ្នាំ:",
    "Update": "ធ្វើបច្ចុប្បន្នភាព",
    "No members in this group": "គ្មានសមាជិកក្នុងក្រុមនេះ",
    "account": "គណនី",
    "doesn't exist in table": "មិនមាននៅក្នុងតារាង",
    "No accounts found.": "រកមិនឃើញគណនី។",
    "No accounts match your search.": "រកមិនឃើញគណនីដែលត្រូវនឹងការស្វែងរករបស់អ្នក។",
    "Inactive": "អសកម្ម",
    "Active": "សកម្ម",
    "This section isn't wired up in the preview yet — it would live here, styled to match the rest of the dashboard.": "ផ្នែកនេះមិនទាន់ត្រូវបានតភ្ជាប់ក្នុងការបង្ហាញជាមុននៅឡើយទេ — វានឹងស្ថិតនៅទីនេះ តុបតែងឱ្យសមនឹងផ្ទាំងគ្រប់គ្រងទាំងមូល។",
    "Failed to load dashboard data. Make sure the backend server is running.": "ការទាញយកទិន្នន័យផ្ទាំងគ្រប់គ្រងបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Expand sidebar": "ពង្រីករបារចំហៀង",
    "Collapse sidebar": "បង្រួមរបារចំហៀង",
    "Admin:": "អ្នកគ្រប់គ្រង:",
    "Admin": "អ្នកគ្រប់គ្រង",
    "Welcome Admin Dashboard": "សូមស្វាគមន៍មកកាន់ផ្ទាំងគ្រប់គ្រង",
    "CIU System Admin": "អ្នកគ្រប់គ្រងប្រព័ន្ធ CIU",
    "Total Overall": "សរុបទាំងអស់",
    "Total Teachers": "គ្រូសរុប",
    "Total Students": "សិស្សសរុប",
    "Total Every Year": "សរុបតាមឆ្នាំ",
    "Total Amount in a Month": "ចំនួនសរុបក្នុងមួយខែ",
    "Total in a Year": "សរុបក្នុងមួយឆ្នាំ",
    "Student and System Amount": "ចំនួនសិស្ស និងប្រព័ន្ធ",
    "Earning — Last Months": "ប្រាក់ចំណូល — ខែមុនៗ",
    "Search students attendance...": "ស្វែងរកវត្តមានសិស្ស...",
    "No attendance records found.": "រកមិនឃើញកំណត់ត្រាវត្តមាន។",
    "Search teachers attendance...": "ស្វែងរកវត្តមានគ្រូ...",
    "Search student by ID, name, email...": "ស្វែងរកសិស្សតាមលេខសម្គាល់ ឈ្មោះ អ៊ីមែល...",
    "Student Accounts": "គណនីសិស្ស",
    "Search teacher by ID, name, email...": "ស្វែងរកគ្រូតាមលេខសម្គាល់ ឈ្មោះ អ៊ីមែល...",
    "Teacher Accounts": "គណនីគ្រូ",
    "Search admin by ID, name, email...": "ស្វែងរកអ្នកគ្រប់គ្រងតាមលេខសម្គាល់ ឈ្មោះ អ៊ីមែល...",
    "Admin Accounts": "គណនីអ្នកគ្រប់គ្រង",

    // Admin: User management
    "Failed to load users. Make sure the backend server is running.": "ការទាញយកអ្នកប្រើបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "User updated successfully.": "អ្នកប្រើត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។",
    "Failed to update user. Please try again.": "ការធ្វើបច្ចុប្បន្នភាពអ្នកប្រើបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "User": "អ្នកប្រើ",
    "deleted successfully.": "ត្រូវបានលុបដោយជោគជ័យ។",
    "restored.": "ត្រូវបានស្តារឡើងវិញ។",
    "Failed to delete user. Please try again.": "ការលុបអ្នកប្រើបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Failed to restore user. Please try again.": "ការស្តារអ្នកប្រើឡើងវិញបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "suspended.": "ត្រូវបានផ្អាក។",
    "Failed to suspend user. Please try again.": "ការផ្អាកអ្នកប្រើបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Search users by ID, name, email...": "ស្វែងរកអ្នកប្រើតាមលេខសម្គាល់ ឈ្មោះ អ៊ីមែល...",
    "Registered Users": "អ្នកប្រើដែលបានចុះឈ្មោះ",
    "Role": "តួនាទី",
    "Created": "បានបង្កើត",
    "Actions": "សកម្មភាព",
    "Edit": "កែសម្រួល",
    "Restore": "ស្តារឡើងវិញ",
    "Suspend": "ផ្អាក",
    "Delete": "លុប",
    "No users match": "គ្មានអ្នកប្រើដែលត្រូវគ្នា",
    "No registered users found.": "រកមិនឃើញអ្នកប្រើដែលបានចុះឈ្មោះ។",
    "Edit User": "កែសម្រួលអ្នកប្រើ",
    "Active account": "គណនីសកម្ម",
    "Saving...": "កំពុងរក្សាទុក...",
    "Suspend Account": "ផ្អាកគណនី",
    "Suspending": "កំពុងផ្អាក",
    "They will not be able to log in until the account is restored.": "ពួកគេនឹងមិនអាចចូលបានទេ រហូតដល់គណនីត្រូវបានស្តារឡើងវិញ។",
    "Message to the user": "សារទៅកាន់អ្នកប្រើ",
    "e.g. Your account has been suspended for 1 week. Reason: breaking school rules.": "ឧ. គណនីរបស់អ្នកត្រូវបានផ្អាករយៈពេល ១ សប្តាហ៍។ ហេតុផល៖ បំពានច្បាប់សាលា។",
    "Suspending...": "កំពុងផ្អាក...",
    "Delete user?": "លុបអ្នកប្រើ?",
    "Restore user?": "ស្តារអ្នកប្រើឡើងវិញ?",
    "Are you sure you want to permanently delete": "តើអ្នកប្រាកដថាចង់លុបជាអចិន្ត្រៃយ៍",
    "This cannot be undone.": "សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។",
    "They will be able to log in again.": "ពួកគេនឹងអាចចូលបានវិញ។",

    // Admin: Course management
    "Failed to load courses. Make sure the backend server is running.": "ការទាញយកវគ្គសិក្សាបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Course code and title are required.": "លេខកូដវគ្គ និងចំណងជើងត្រូវបានទាមទារ។",
    "created successfully.": "ត្រូវបានបង្កើតដោយជោគជ័យ។",
    "updated successfully.": "ត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។",
    "Failed to create course. Please try again.": "ការបង្កើតវគ្គសិក្សាបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Failed to update course. Please try again.": "ការធ្វើបច្ចុប្បន្នភាពវគ្គសិក្សាបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Failed to delete course. Please try again.": "ការលុបវគ្គសិក្សាបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Manage university courses, credits, and instructors.": "គ្រប់គ្រងវគ្គសិក្សាសាកលវិទ្យាល័យ ក្រេឌីត និងគ្រូបង្រៀន។",
    "Search courses...": "ស្វែងរកវគ្គសិក្សា...",
    "Add Course": "បន្ថែមវគ្គសិក្សា",
    "No courses match": "គ្មានវគ្គដែលត្រូវគ្នា",
    "No courses found. Click \"Add Course\" to create one.": "រកមិនឃើញវគ្គសិក្សា។ ចុច \"Add Course\" ដើម្បីបង្កើតមួយ។",
    "Edit Course": "កែសម្រួលវគ្គសិក្សា",
    "Course title": "ចំណងជើងវគ្គ",
    "e.g. Introduction to Computer Science": "ឧ. សេចក្តីផ្តើមវិទ្យាសាស្ត្រកុំព្យូទ័រ",
    "e.g. Mr. Rady Chan": "ឧ. លោក រ៉ាឌី ចាន់",
    "Description": "ការពិពណ៌នា",
    "Short description of the course": "ការពិពណ៌នាខ្លីនៃវគ្គ",
    "Toggle active": "បិទ/បើកសកម្ម",
    "Save Course": "រក្សាទុកវគ្គ",
    "Delete course?": "លុបវគ្គ?",
    "Are you sure you want to permanently delete course": "តើអ្នកប្រាកដថាចង់លុបវគ្គជាអចិន្ត្រៃយ៍",

    // Admin: News management
    "Failed to load news. Make sure the backend server is running.": "ការទាញយកព័ត៌មានបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "News title and content are required.": "ចំណងជើងព័ត៌មាន និងខ្លឹមសារត្រូវបានទាមទារ។",
    'News "': 'ព័ត៌មាន "',
    '" published successfully.': '" ត្រូវបានបោះពុម្ពដោយជោគជ័យ។',
    '" updated successfully.': '" ត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។',
    "Failed to publish news. Please try again.": "ការបោះពុម្ពព័ត៌មានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Failed to update news. Please try again.": "ការធ្វើបច្ចុប្បន្នភាពព័ត៌មានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    '" deleted successfully.': '" ត្រូវបានលុបដោយជោគជ័យ។',
    "Failed to delete news. Please try again.": "ការលុបព័ត៌មានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Publish and manage news articles shown on the homepage.": "បោះពុម្ព និងគ្រប់គ្រងអត្ថបទព័ត៌មានដែលបង្ហាញនៅលើទំព័រដើម។",
    "Search news...": "ស្វែងរកព័ត៌មាន...",
    "Post News": "ប្រកាសព័ត៌មាន",
    "News Posts (": "ប្រកាសព័ត៌មាន (",
    ")": ")",
    "Author": "អ្នកនិពន្ធ",
    "Draft": "សេចក្តីព្រាង",
    "Published": "បានបោះពុម្ព",
    'No news match "': 'គ្មានព័ត៌មានដែលត្រូវគ្នា "',
    '".': '".',
    'No news yet. Click "Post News" to publish the first article.': 'មិនទាន់មានព័ត៌មាននៅឡើយទេ។ ចុច "Post News" ដើម្បីបោះពុម្ពអត្ថបទដំបូង។',
    "Edit News #": "កែសម្រួលព័ត៌មាន #",
    "e.g. Admin": "ឧ. អ្នកគ្រប់គ្រង",
    "e.g. CIU wins national coding competition": "ឧ. CIU ឈ្នះការប្រកួតសរសេរកូដថ្នាក់ជាតិ",
    "Image URL": "តំណរូបភាព",
    "Content": "ខ្លឹមសារ",
    "Write the news article content...": "សរសេរខ្លឹមសារអត្ថបទព័ត៌មាន...",
    "Toggle published": "បិទ/បើកការបោះពុម្ព",
    "Published (visible on homepage)": "បានបោះពុម្ព (មើលឃើញនៅលើទំព័រដើម)",
    "Draft (hidden on homepage)": "សេចក្តីព្រាង (លាក់ពីទំព័រដើម)",
    "Publish News": "បោះពុម្ពព័ត៌មាន",
    "Delete news post?": "លុបប្រកាសព័ត៌មាន?",
    "Are you sure you want to permanently delete news post": "តើអ្នកប្រាកដថាចង់លុបប្រកាសព័ត៌មានជាអចិន្ត្រៃយ៍",
    "? This cannot be undone.": "? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។",

    // Admin: Audit log
    "Failed to load audit logs. Make sure the backend server is running.": "ការទាញយកកំណត់ហេតុសវនកម្មបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Audit logs cleared successfully.": "កំណត់ហេតុសវនកម្មត្រូវបានសម្អាតដោយជោគជ័យ។",
    "Failed to clear audit logs. Please try again.": "ការសម្អាតកំណត់ហេតុសវនកម្មបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Record of admin actions performed across the system.": "កំណត់ត្រានៃសកម្មភាពអ្នកគ្រប់គ្រងដែលបានធ្វើនៅទូទាំងប្រព័ន្ធ។",
    "Search logs...": "ស្វែងរកកំណត់ហេតុ...",
    "All actions": "សកម្មភាពទាំងអស់",
    "Clear Logs": "សម្អាតកំណត់ហេតុ",
    "Audit Logs (": "កំណត់ហេតុសវនកម្ម (",
    "Timestamp": "ពេលវេលា",
    "Actor": "អ្នកធ្វើសកម្មភាព",
    "Action": "សកម្មភាព",
    "Target": "គោលដៅ",
    "Details": "ព័ត៌មានលម្អិត",
    "IP": "IP",
    "No logs match your filters.": "គ្មានកំណត់ហេតុដែលត្រូវនឹងតម្រងរបស់អ្នក។",
    "No logs match your search.": "គ្មានកំណត់ហេតុដែលត្រូវនឹងការស្វែងរករបស់អ្នក។",
    "No audit logs recorded yet.": "មិនទាន់មានកំណត់ហេតុសវនកម្មនៅឡើយទេ។",
    "Clear all audit logs?": "សម្អាតកំណត់ហេតុសវនកម្មទាំងអស់?",
    "This will permanently remove all": "វានឹងលុបចោលជាអចិន្ត្រៃយ៍",
    "recorded log entry.": "កំណត់ត្រាកំណត់ហេតុ។",
    "recorded log entries.": "កំណត់ត្រាកំណត់ហេតុទាំងអស់។",

    // Admin: Contact inbox
    "Please fill in both the subject and your reply.": "សូមបំពេញទាំងប្រធានបទ និងការឆ្លើយតបរបស់អ្នក។",
    "Reply sent to": "បានផ្ញើការឆ្លើយតបទៅកាន់",
    "Backend reply failed — opened your mail app instead.": "ការឆ្លើយតបពីម៉ាស៊ីនមេបរាជ័យ — បានបើកកម្មវិធីអ៊ីមែលរបស់អ្នកជំនួសវិញ។",
    "Contact Messages": "សារទំនាក់ទំនង",
    "Search messages...": "ស្វែងរកសារ...",
    "New Message": "សារថ្មី",
    "No messages match your search.": "គ្មានសារដែលត្រូវនឹងការស្វែងរករបស់អ្នក។",
    "Reply": "ឆ្លើយតប",
    "Delete Message": "លុបសារ",
    "Select a message to read it here.": "ជ្រើសរើសសារដើម្បីអាននៅទីនេះ។",
    "Reply to": "ឆ្លើយតបទៅកាន់",
    "To:": "ទៅកាន់:",
    "Subject": "ប្រធានបទ",
    "Write your reply message...": "សរសេរសារឆ្លើយតបរបស់អ្នក...",
    "Send Reply": "ផ្ញើការឆ្លើយតប",

    // Admin: Enrollment management
    "Enrollment for": "ការចុះឈ្មោះសម្រាប់",
    "approved": "ត្រូវបានអនុម័ត",
    "rejected": "ត្រូវបានបដិសេធ",
    "Approved": "បានអនុម័ត",
    "Rejected": "បានបដិសេធ",
    "Pending": "កំពុងរង់ចាំ",
    "Enrollment Requests": "សំណើចុះឈ្មោះ",
    "Search by name, ID, course...": "ស្វែងរកតាមឈ្មោះ លេខសម្គាល់ វគ្គ...",
    "Total": "សរុប",
    "Approve": "អនុម័ត",
    "Reject": "បដិសេធ",
    "No enrollments match your search.": "គ្មានការចុះឈ្មោះដែលត្រូវនឹងការស្វែងរករបស់អ្នក។",

    // Misc pieces
    ".": ".",
    "About Us": "អំពីយើង",
    "FAQ": "សំណួរញឹកញាប់",
    "Email": "អ៊ីមែល",
    "Course": "វគ្គសិក្សា",
    "Enroll": "ចុះឈ្មោះ",
    "Logout": "ចាកចេញ",
    "Student": "សិស្ស",
    "Loading...": "កំពុងផ្ទុក...",
    "Attendance saved locally. Backend save failed.": "បានរក្សាទុកវត្តមានក្នុងម៉ាស៊ីន។ ការរក្សាទុកទៅម៉ាស៊ីនមេបរាជ័យ។",
    "Enter at least one grade before submitting.": "សូមបញ្ចូលពិន្ទុយ៉ាងហោចណាស់មួយ មុនពេលដាក់ស្នើ។",
    "Grades submitted successfully.": "ពិន្ទុត្រូវបានដាក់ស្នើដោយជោគជ័យ។",
    "Grades saved locally. Backend submit failed.": "បានរក្សាទុកពិន្ទុក្នុងម៉ាស៊ីន។ ការដាក់ស្នើទៅម៉ាស៊ីនមេបរាជ័យ។",
    "Please fill in both the title and the message.": "សូមបំពេញទាំងចំណងជើង និងសារ។",
    "Announcement posted successfully.": "ការប្រកាសត្រូវបានបង្ហោះដោយជោគជ័យ។",
    "Failed to post announcement. Make sure the backend server is running.": "ការបង្ហោះការប្រកាសបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Announcement title": "ចំណងជើងការប្រកាស",
    "Write your announcement here...": "សរសេរការប្រកាសរបស់អ្នកនៅទីនេះ...",
    "Submitting...": "កំពុងដាក់ស្នើ...",
    "Posting...": "កំពុងបង្ហោះ...",
    "Post": "បង្ហោះ",

    // Assignments
    "Assignment": "កិច្ចការ",
    "Assignments": "កិច្ចការ",
    "New Assignment": "កិច្ចការថ្មី",
    "Assignment title": "ចំណងជើងកិច្ចការ",
    "Submit Assignment": "ដាក់ស្នើកិច្ចការ",
    "Submission note (optional)": "កំណត់ចំណាំដាក់ស្នើ (ស្រេចចិត្ត)",
    "Add a note to your submission...": "បន្ថែមកំណត់ចំណាំទៅការដាក់ស្នើរបស់អ្នក...",
    "Due": "កំណត់",
    "Assignment created.": "កិច្ចការត្រូវបានបង្កើត។",
    "Assignment deleted.": "កិច្ចការត្រូវបានលុប។",
    "Assignment submitted successfully.": "កិច្ចការត្រូវបានដាក់ស្នើដោយជោគជ័យ។",
    "Failed to create assignment. Make sure the backend server is running.": "ការបង្កើតកិច្ចការបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Failed to submit assignment. Make sure the backend server is running.": "ការដាក់ស្នើកិច្ចការបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Please fill in both the title and the due date.": "សូមបំពេញទាំងចំណងជើង និងកាលបរិច្ឆេទកំណត់។",
    "No assignments yet": "មិនទាន់មានកិច្ចការនៅឡើយទេ",
    "Submissions": "ការដាក់ស្នើ",
    "Submitted": "បានដាក់ស្នើ",
    "Submit": "ដាក់ស្នើ",

    // Attendance
    "My Attendance": "វត្តមានរបស់ខ្ញុំ",
    "All present": "វត្តមានទាំងអស់",
    "All absent": "អវត្តមានទាំងអស់",
    "Low attendance": "វត្តមានទាប",
    "No attendance data yet": "មិនទាន់មានទិន្នន័យវត្តមាននៅឡើយទេ",

    // Invoices / income
    "Invoice": "វិក្កយបត្រ",
    "Invoices": "វិក្កយបត្រ",
    "No invoices yet": "មិនទាន់មានវិក្កយបត្រនៅឡើយទេ",
    "Total Billed": "ចំនួនសរុបវិក្កយបត្រ",
    "Total Income": "ចំណូលសរុប",
    "Completed payments": "ការទូទាត់ដែលបានបញ្ចប់",
    "Outstanding": "នៅសល់",
    "Unpaid balance": "សមតុល្យដែលមិនទាន់បង់",
    "Overdue": "ហួសកំណត់",
    "Monthly Average": "មធ្យមភាគប្រចាំខែ",
    "Income": "ចំណូល",
    "Export Earnings CSV": "នាំចេញ CSV នៃចំណូល",

    // Messages / chat
    "Messages": "សារ",
    "Message": "សារ",
    "Class Messages": "សារថ្នាក់",
    "Type a message...": "វាយសារ...",
    "No messages yet": "មិនទាន់មានសារនៅឡើយទេ",
    "Send": "ផ្ញើ",
    "Message saved locally. Backend send failed.": "សារត្រូវបានរក្សាទុកក្នុងម៉ាស៊ីន។ ការផ្ញើទៅម៉ាស៊ីនមេបរាជ័យ។",
    "Inbox": "ប្រអប់សារ",
    "Read": "អាន",
    "Unread": "មិនទាន់អាន",
    "Select message": "ជ្រើសរើសសារ",
    "Select all": "ជ្រើសរើសទាំងអស់",
    "Deselect all": "ឈប់ជ្រើសរើសទាំងអស់",
    "Mark read": "សម្គាល់ថាបានអាន",
    "Mark all read": "សម្គាល់ថាបានអានទាំងអស់",
    "Selected messages marked as read.": "សារដែលបានជ្រើសរើសត្រូវបានសម្គាល់ថាបានអាន។",
    "Selected messages deleted.": "សារដែលបានជ្រើសរើសត្រូវបានលុប។",
    "You": "អ្នក",

    // Notifications
    "Notifications": "ការជូនដំណឹង",
    "Broadcast Notification": "ការជូនដំណឹងផ្សាយ",
    "Broadcast": "ផ្សាយ",
    "Send Broadcast": "ផ្ញើការផ្សាយ",
    "Audience": "ទស្សនិកជន",
    "Write the notification message...": "សរសេរសារជូនដំណឹង...",
    "Search notifications...": "ស្វែងរកការជូនដំណឹង...",
    "No notifications": "គ្មានការជូនដំណឹង",
    "No notifications yet.": "មិនទាន់មានការជូនដំណឹងនៅឡើយទេ។",
    "No notifications match your search.": "គ្មានការជូនដំណឹងដែលត្រូវនឹងការស្វែងរករបស់អ្នកទេ។",
    "All notifications marked as read.": "សារជូនដំណឹងទាំងអស់ត្រូវបានសម្គាល់ថាបានអាន។",
    "Notification broadcast sent successfully.": "ការជូនដំណឹងត្រូវបានផ្សាយដោយជោគជ័យ។",
    "Failed to send broadcast. Make sure the backend server is running.": "ការផ្ញើការផ្សាយបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Notification title and message are required.": "ចំណងជើង និងសារជូនដំណឹងត្រូវបានទាមទារ។",
    "Broadcast announcements and manage notifications sent to students and staff.": "ផ្សាយការប្រកាស និងគ្រប់គ្រងការជូនដំណឹងដែលផ្ញើទៅសិស្ស និងបុគ្គលិក។",
    "Backend offline — showing sample notifications.": "ម៉ាស៊ីនមេឈប់ដំណើរការ — កំពុងបង្ហាញការជូនដំណឹងគំរូ។",
    "Mobile navigation": "ការរុករកទូរសព្ទ",

    // Reports
    "All reports": "របាយការណ៍ទាំងអស់",
    "Total reports": "របាយការណ៍សរុប",
    "Search reports...": "ស្វែងរករបាយការណ៍...",
    "No reports match your filters.": "គ្មានរបាយការណ៍ដែលត្រូវនឹងតម្រងរបស់អ្នកទេ។",
    "No reports match your search.": "គ្មានរបាយការណ៍ដែលត្រូវនឹងការស្វែងរករបស់អ្នកទេ។",
    "No reports submitted yet.": "មិនទាន់មានរបាយការណ៍ដាក់ស្នើនៅឡើយទេ។",
    "Resolve": "ដោះស្រាយ",
    "Resolved": "បានដោះស្រាយ",
    "Reopen": "បើកឡើងវិញ",
    "Report marked as resolved.": "របាយការណ៍ត្រូវបានសម្គាល់ថាបានដោះស្រាយ។",
    "Report marked as unread.": "របាយការណ៍ត្រូវបានសម្គាល់ថាមិនទាន់អាន។",
    "Applicant": "អ្នកដាក់ពាក្យ",
    "Student-submitted reports and requests from across the university.": "របាយការណ៍ និងសំណើដែលបញ្ជូនដោយសិស្សពីទូទាំងសាកលវិទ្យាល័យ។",
    "Backend offline — showing sample reports.": "ម៉ាស៊ីនមេឈប់ដំណើរការ — កំពុងបង្ហាញរបាយការណ៍គំរូ។",

    // Schedule
    "Weekly Schedule": "កាលវិភាគប្រចាំសប្តាហ៍",
    "Save Schedule": "រក្សាទុកកាលវិភាគ",
    "Add Row": "បន្ថែមជួរ",
    "Day": "ថ្ងៃ",
    "Time": "ម៉ោង",
    "Room": "បន្ទប់",
    "Instructor name": "ឈ្មោះគ្រូបង្រៀន",
    "Save": "រក្សាទុក",
    "Remove": "លុប",
    "No schedule available yet": "មិនទាន់មានកាលវិភាគនៅឡើយទេ",
    "No schedule entries yet. Click": "មិនទាន់មានកាលវិភាគនៅឡើយទេ។ ចុច",
    "to build the schedule.": "ដើម្បីបង្កើតកាលវិភាគ។",
    "Every schedule entry needs a course code.": "រាល់ការបញ្ចូលកាលវិភាគត្រូវការលេខកូដវគ្គសិក្សា។",
    "Schedule saved successfully.": "កាលវិភាគត្រូវបានរក្សាទុកដោយជោគជ័យ។",
    "Schedule saved locally. Backend save failed — it will still be shown to students.": "កាលវិភាគត្រូវបានរក្សាទុកក្នុងម៉ាស៊ីន។ ការរក្សាទុកទៅម៉ាស៊ីនមេបរាជ័យ — វានឹងនៅតែបង្ហាញដល់សិស្ស។",
    "Scheduled": "បានកំណត់ពេល",
    "Backend offline — showing a sample schedule.": "ម៉ាស៊ីនមេឈប់ដំណើរការ — កំពុងបង្ហាញកាលវិភាគគំរូ។",
    "Build and edit the weekly class schedule shown to students and teachers.": "បង្កើត និងកែសម្រួលកាលវិភាគថ្នាក់ប្រចាំសប្តាហ៍ដែលបង្ហាញដល់សិស្ស និងគ្រូ។",
    "Month": "ខែ",

    // Announcement management
    "Edit Announcement": "កែសម្រួលការប្រកាស",
    "Announcement updated.": "ការប្រកាសត្រូវបានធ្វើបច្ចុប្បន្នភាព។",
    "Announcement deleted.": "ការប្រកាសត្រូវបានលុប។",
    "Failed to save announcement. Make sure the backend server is running.": "ការរក្សាទុកការប្រកាសបរាជ័យ។ សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "No announcements yet": "មិនទាន់មានការប្រកាសនៅឡើយទេ",

    // CSV / users
    "Export CSV": "នាំចេញ CSV",
    "Import CSV": "នាំចូល CSV",
    "Download / Print": "ទាញយក / បោះពុម្ព",
    "Imported": "បាននាំចូល",
    "Users exported successfully.": "អ្នកប្រើត្រូវបាននាំចេញដោយជោគជ័យ។",
    "Failed to export users. Please try again.": "ការនាំចេញអ្នកប្រើបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Failed to import users. Check that the CSV has a header row with username, email, phone, role.": "ការនាំចូលអ្នកប្រើបរាជ័យ។ សូមពិនិត្យថា CSV មានជួរក្បាលដែលមាន username, email, phone, role។",
    "Batch": "ក្រុម",
    "Approve all": "អនុម័តទាំងអស់",
    "Reject all": "បដិសេធទាំងអស់",

    // Course / featured toggles
    "Feature": "លក្ខណៈពិសេស",
    "Featured": "ពិសេស",
    "Featured on homepage": "បង្ហាញនៅទំព័រដើម",
    "Not featured": "មិនពិសេស",
    "Toggle featured": "ប្តូរស្ថានភាពពិសេស",
    "Unfeature": "ដកចេញពីពិសេស",
    "Enable": "បើក",
    "Disable": "បិទ",
    "enabled": "ត្រូវបានបើក",
    "disabled": "ត្រូវបានបិទ",
    "featured on homepage": "ត្រូវបានបង្ហាញនៅទំព័រដើម",
    "unfeatured": "មិនត្រូវបានបង្ហាញនៅទំព័រដើម",
    "Failed to update course status. Please try again.": "ការធ្វើបច្ចុប្បន្នភាពស្ថានភាពវគ្គសិក្សាបរាជ័យ។ សូមព្យាយាមម្តងទៀត។",
    "Create": "បង្កើត",
    "Creating...": "កំពុងបង្កើត...",
    "Checking...": "កំពុងពិនិត្យ...",

    // Applications / scholarships
    "Scholarship": "អាហារូបករណ៍",
    "Apply for a Scholarship": "ដាក់ពាក្យសុំអាហារូបករណ៍",
    "Submit Application": "ដាក់ស្នើពាក្យសុំ",
    "Application type": "ប្រភេទពាក្យសុំ",
    "Application code": "លេខកូដពាក្យសុំ",
    "Check Application Status": "ពិនិត្យស្ថានភាពពាក្យសុំ",
    "Check Status": "ពិនិត្យស្ថានភាព",
    "Intended program": "កម្មវិធីដែលចង់សិក្សា",
    "Application submitted successfully. Our team will contact you soon.": "ពាក្យសុំត្រូវបានដាក់ស្នើដោយជោគជ័យ។ ក្រុមការងាររបស់យើងនឹងទាក់ទងអ្នកឆាប់ៗ។",
    "Enter the application code you received when you submitted your enrollment or scholarship application.": "បញ្ចូលលេខកូដពាក្យសុំដែលអ្នកបានទទួលនៅពេលអ្នកដាក់ពាក្យចុះឈ្មោះ ឬសុំអាហារូបករណ៍។",
    "No application found with that code.": "រកមិនឃើញពាក្យសុំដែលមានលេខកូដនោះទេ។",
    "Backend lookup failed — make sure the backend server is running.": "ការស្វែងរកពីម៉ាស៊ីនមេបរាជ័យ — សូមប្រាកដថាម៉ាស៊ីនមេកំពុងដំណើរការ។",
    "Please enter your application code.": "សូមបញ្ចូលលេខកូដពាក្យសុំរបស់អ្នក។",
    "Please fill in your name and a valid email address.": "សូមបំពេញឈ្មោះ និងអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវរបស់អ្នក។",
    "Please enter a valid email address.": "សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវ។",
    "Tell us about your academic background and why you qualify...": "ប្រាប់យើងអំពីប្រវត្តិសិក្សារបស់អ្នក និងមូលហេតុដែលអ្នកមានលក្ខណៈសម្បត្តិ...",
    "Fill in the form below and our admissions team will contact you with the next steps.": "សូមបំពេញទម្រង់ខាងក្រោម ហើយក្រុមការងារចុះឈ្មោះរបស់យើងនឹងទាក់ទងអ្នកជាមួយជំហានបន្ទាប់។",
    "Thanks! You're on the list.": "អរគុណ! អ្នកបានចុះឈ្មោះរួចហើយ។",
    "Publish on (optional)": "ផ្សាយនៅថ្ងៃ (ស្រេចចិត្ត)",
    "Leave empty to publish immediately. Setting a date schedules the post.": "ទុកទទេដើម្បីផ្សាយភ្លាមៗ។ ការកំណត់កាលបរិច្ឆេទនឹងកំណត់ពេលផ្សាយ។",

    // Homepage catalog
    "allCourses": "វគ្គសិក្សាទាំងអស់",
    "inCategory": "ក្នុងប្រភេទ",

    // Fragment keys used inside concatenated strings
    "pending enrollment(s).": "ការចុះឈ្មោះដែលកំពុងរង់ចាំ។",
    "user(s) successfully.": "អ្នកប្រើដោយជោគជ័យ។",
    "invoice(s)": "វិក្កយបត្រ",
    "messages": "សារ",
    "Weekly Schedule (": "កាលវិភាគប្រចាំសប្តាហ៍ (",
    "Reports (": "របាយការណ៍ (",
    "Rate": "អត្រា",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return sessionStorage.getItem("lang") || "en";
  });

  useEffect(() => {
    sessionStorage.setItem("lang", lang);
    document.documentElement.lang = lang === "kh" ? "km" : "en";
  }, [lang]);

  const t = (key) => (DICT[lang] && DICT[lang][key]) || DICT.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
